spec-version: 0.30.0
name: linalg
author: Asad Saeeduddin
maintainer: masaeedu@gmail.com
license: MIT

build-type: Simple

source-dirs: src
dependencies:
  - { name: "base", version: ">=4.12 && <4.13" }
  - { name: "vector", version: ">=0.12.0 && <0.12.1" }
  - { name: "fin", version: ">=0.1 && <0.2" }
  - { name: "vec", version: ">=0.3 && <0.4" }

ghc-options: -Wall
default-extensions:
  - GADTs

  - StandaloneDeriving
  - DeriveFunctor
  - DerivingVia
  - GeneralizedNewtypeDeriving

  - ScopedTypeVariables
  - RankNTypes
  - QuantifiedConstraints

  - TypeApplications
  - TypeOperators
  - MultiParamTypeClasses

  - ConstraintKinds
  - DataKinds
  - PolyKinds
  - KindSignatures

  - UndecidableInstances
  - FlexibleInstances
  - FlexibleContexts
  - DefaultSignatures

  - NoImplicitPrelude

library: {}
executable:
  source-dirs: test
  main: Main.hs
  dependencies:
    - linalg
    - time
